### ISSUE TITLE
[rojak-pantau] Rojak Pantau Architecture

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#10]
@imrenagi We need to discuss the architecture of `rojak-pantau` and `rojak-analyzer`.

Kita punya beberapa approach yang mungkin kita bisa pilih. Tapi kita mulai dari tujuannya dulu: Kita pengen scalable, kita pengen bisa run a bunch of `rojak-pantau` dan `rojak-analyzer` dengan mudah.

Untuk approach pertama, yg paling naive kaya gini:
![rojak pantau rojak analyzer arch 1 1](https://cloud.githubusercontent.com/assets/2213646/19079401/b6120344-8a7d-11e6-88ab-f706af29a0bb.jpg)

Untuk trade-off nya: `rojak-pantau` depend ke `rojak-analyzer` yang artinya`rojak-analyzer` fail `rojak-pantau` akan fail juga

Untuk yg approach kedua seperti ini:

![rojak pantau rojak analyzer arch 2 1](https://cloud.githubusercontent.com/assets/2213646/19079539/29a30a06-8a7e-11e6-99be-e28a45b5e8f0.jpg)

Ini solve masalah di approach pertama sih, tapi mungkin lebih kompleks.

enaknya pake yang mana ya?

**Comment by pyk** [comment]
Oh ya untuk gambarnya bisa diedit di [Fig 1](https://docs.google.com/drawings/d/1bBe-rFAOKWRVCrI9PE1hqRx43CqdrJmNw-S2BfkyesQ/edit?usp=sharing) dan [Fig 2](https://docs.google.com/drawings/d/1XcU7A66UonyVM3UW1b3DaPJ62dLPBc0ih2kq7dj5sKQ/edit?usp=sharing)

**Comment by imrenagi** [comment]
utk metode 2, data hasil scrappingnya mau disimpen juga @pyk ? Sebenernya emg lebih tahan nomer 2 sih kalau ada apa2. tapi orchestasinya mungkin bakalan lebih ribet.

kalau pakai metode web scrapping sistemnya batch processing gak sih?  jadi kalau seandainya metode 1 si `pantau`nya down, kita tinggal ulang tasknya aja. simplenya gitu.

**Comment by pyk** [comment]
> utk metode 2, data hasil scrappingnya mau disimpen juga @pyk ?

Iya mas, nanti bisa di gunain lagi, misal untuk diambil topicnya/issue dll.

> Sebenernya emg lebih tahan nomer 2 sih kalau ada apa2. tapi orchestasinya mungkin bakalan lebih ribet.

Setuju mas, waktu deployment nya yg agak ribet.

> kalau pakai metode web scrapping sistemnya batch processing gak sih? jadi kalau seandainya metode 1 si pantaunya down, kita tinggal ulang tasknya aja. simplenya gitu.

hmmm jadi kalau pas analyzer fail, proses retrieval datanya stop dong mas?

**Comment by imrenagi** [comment]
> hmmm jadi kalau pas analyzer fail, proses retrieval datanya stop dong mas?

hmmm bentar kok bahasannya jadi analyzer fail? apa gw ada yg skip? 

> Untuk trade-off nya: rojak-pantau depend ke rojak-analyzer yang artinya rojak-analyzer fail rojak-pantau akan fail juga

kalau dari diagram itu gw ngartiinnya `analyzer` bakalan jalan kalau ada triger dari `pantau`. Berarti kalau analyzernya yg failed tergantung si `pantau` (dalam kasus ini sbg data fetchernya) maunya gimana. Soalnya datanya kan udah ada di pantau.

**Comment by pyk** [comment]
> Berarti kalau analyzernya yg failed tergantung si pantau (dalam kasus ini sbg data fetchernya) maunya gimana. Soalnya datanya kan udah ada di pantau.

Iya mas datanya sudah ada di pantau, tapi gak bisa di masukin di database. Karena di nomor 1 itu cuman berita yg masuk aja yg ada di database.

Menurutku mending kita pake yg no 2 sih mas, untuk queue nya kita pake ini aja https://nats.io/documentation/concepts/nats-queueing/ (pake yg docker)

Alasan pake no 2 karena kita bisa pantau terus, terus di analisa secara offline. How?

**Comment by imrenagi** [comment]
> Alasan pake no 2 karena kita bisa pantau terus, terus di analisa secara offline. How?

Setuju. offline dulu aja bay.

**Comment by pyk** [comment]
Woke, sep. Jadi kesimpulannya kita akan pake Architecture no 2 untuk `rojak-queue` kita pake ini https://nats.io/documentation/concepts/nats-queueing/ 

Thanks mas! 🙇
