### ISSUE TITLE
[rojak-api] API spec v0.2 discussion

### ISSUE THREAD

**Issue by bobbypriam** [pyk/rojak#106]
Spesifikasi awal sudah dilakukan di #36. Namun ada beberapa hal yang membuat spesifikasi sekarang sepertinya kurang spesifik dan cenderung banyak redundansi. Isu ini ditujukan untuk mendiskusikan revisi spesifikasi tersebut.

Edit: Untuk memudahkan, kita akan pakai versioning untuk spesifikasi (yang mungkin akan berbeda dengan version schema data dan implementasinya). Ini akan jadi **v0.2**, dan spesifikasi pada #36 kita sebut sebagai **v0.1**. Di paling bawah revisi ini juga terdapat summary perubahan yang dilakukan dari v0.1.
# Revisi

Approach kali ini lebih adhoc, lebih fokus dengan apa yang ingin didapatkan (dibanding terfokus harus RESTful). Di sini kita juga lebih nge-treat `sentiment` sebagai first-class citizen, jadi hampir di semua resource (`pairing`, `candidate`, `news`) kita akan ada embedded `sentiment`-nya. Untuk teman-teman dari tim **rojak-ui-***, mungkin bisa coba lihat apakah use case yang akan ada di UI sudah bisa didapat melalui endpoint-endpoint ini atau belum.
### Information on pairs of candidates:

**1. List of pairings**
embeddable: overall sentiment for each pairing

**2. Detail of the pairing - name, website, usernames, slogan, description**
embeddable: cagub & cawagub, overall sentiment for the pairing

**3. Sentiments for the pairing broken down by media**
sortable: sentiment score
### Information on candidates:

**4. List of candidates**
embeddable: overall sentiment for each candidate
sortable: name

**5. Profile of the candidate - name, birth, religion, etc.**
embeddable: pairing detail, overall sentiment for the candidate

**6. Sentiments for the candidate broken down by media**
sortable: sentiment score
### Information on news articles:

**7. List of article**
embeddable: mentioned candidates and sentiment
filterable: media_id, candidate_id(s), pairing_id(s)
sortable: publish time

**8. Article detail - url, media, author, publish time**
embeddable: mentioned candidates and sentiment
### Information on media:

**9. List of media**
sortable: name

**10. Media detail - name, logo, usernames, etc.**

**11. Sentiments breakdown of the running pairs of candidates, can also be broken down for each candidate**
## New endpoint structure

```
/pairings               // 1
  /{pairingId}          // 2
    /media-sentiments   // 3
/candidates             // 4
  /{candidatesId}       // 5
    /media-sentiments   // 6
/news                   // 7
  /{newsId}             // 8
/media                  // 9
  /{mediaId}            // 10
    /sentiments         // 11
```
## Response examples
1. /pairings
   
   ```
     [{
       // pairing details...
       sentiments: {
         positive: 0.123,
         neutral: 0.123,
         negative: 0.123
       }
     }]
   ```
2. /pairings/{pairingId}
   
   ```
     {
       // pairing details...
       sentiments: { // sentiment details },
       candidates: {
         cagub: { // cagub detail },
         cawagub: { // cawagub detail }
       }
     }
   ```
3. /pairings/{pairingId}/media-sentiments
   
   ```
     [{
       // media details
       sentiments: {
         positive: 0.123,
         neutral: 0.123,
         negative: 0.123
       }
     }]
   ```
4. /candidates
   
   ```
     [{
       // candidate details...
       sentiments: { // sentiment details }
     }]
   ```
5. /candidate/{candidateId}
   
   ```
     {
       // candidate details...
       sentiments: { // sentiment details }
       pairing: { // pairing detail }
     }
   ```
6. /candidates/{candidateId}/media-sentiments
   
   ```
     [{
       // media details
       sentiments: {
         positive: 0.123,
         neutral: 0.123,
         negative: 0.123
       }
     }]
   ```
7. /news
   
   ```
     [{
       // news details...
       mentions: [{
         // candidate details
         sentiment: {
           type: 'positive',
           score: 0.123
         }
       }]
     }]
   ```
8. /news/{newsId}
   
   ```
     {
       // news details...
       mentions: [{
         // candidate details
         sentiment: {
           type: 'positive',
           score: 0.123
         }
       }]
     }
   ```
9. /media
   
   ```
     [{
       // media details...
     }]
   ```
10. /media/{mediaId}
    
    ```
      {
        // media details...
      }
    ```
11. /media/{mediaId}/sentiments
    
    ```
      [{
        pairing: {
          // pairing detail
          sentiments: { // sentiments details },
        },
        candidates: {
          cagub: {
            // cagub detail
            sentiments: { // sentiments details }
          },
          cawagub: {
            // cawagub detail
            sentiments: { // sentiments details }
          }
        }
      }]
    ```
## Notable changes dari v0.1
1. `/pairings/{pairingId}/news`, `/candidates/{candidateId}/news`, dan `/media/{mediaId}/news` dihapus, diganti dengan `/news` dengan query parameter `pairing_id`, `candidate_id`, dan `media_id`.
2. Overall sentiment dari `pairing` dan `candidate` akan di-embed pada resourcenya dan tidak perlu endpoint sendiri lagi, sehingga `/pairings/{pairingId}/sentiments` dan `/candidates/{candidateId}/sentiments` dihapus
3. Ada endpoint baru pada `/pairings/{pairingId}/media-sentiments` dan `/candidates/{candidateId}/media-sentiments` yang akan mengembalikan list of `media` beserta sentimennya terhadap `pairing` atau `candidate` tersebut.
4. Endpoint spesifik `/(pairings, candidates)/{id}/sentiments/media*` dihapus, informasinya seharusnya bisa didapat melalui `/media/{mediaId}/sentiments` dan `/news`.
## Post edit logs
- 2016-10-20 20:56 - Simplify struktur response
- 2016-10-18 20:35 - Ubah response example untuk 3, 6, 7, 8, 11 ([lihat ini](https://github.com/pyk/rojak/issues/106#issuecomment-254507647))
- 2016-10-18 20:12 - Tambah version detail dan notable changes
- 2016-10-17 21:00 - Initial description

**Comment by pyk** [comment]
cc @rromadhoni @mychaelgo @adrianha @hidrodixtion

**Comment by mychaelgo** [comment]
btw, itu kan ada sentiment (positive, neutral,negative) nanti mau gambarin di ui nya pakai icon gitu ya?

**Comment by bobbypriam** [comment]
@mychaelgo Presentasinya terserah yang bikin UI sih mas. Menurut temen-temen tim data skor dari sentimen tiap-tiap news punya range `0 <= score <= 1`, jadi representasinya yang dikasih dari API bisa raw desimal atau dalam percentage. Mungkin di UI-nya bisa dalam bentuk chart (bar, donat, star, etc.)?

**Comment by mychaelgo** [comment]
Oh okay, mau nanya untuk yang endpoint 11, apakah memungkinkan 1 media membahas lebih dari 2 candidate?

**Comment by bobbypriam** [comment]
Media tidak membahas candidate, mas, yang membahas candidate itu di `news`. Media hanya punya agregasi sentimen-sentimen dari berita-berita pada media tersebut.

Endpoint 11 akan mengembalikan agregasi itu dalam format array of objects, di mana tiap-tiap object akan mengandung keterangan pasangan dan sentimennya (termasuk breakdown untuk tiap candidate-nya). Kira-kira masuk akal ga mas?

**Comment by bobbypriam** [comment]
Saya baru saja menambahkan keterangan version dari spesifikasi ini dan beberapa poin perubahan sejak versi sebelumnya di post pertama issue ini, mungkin dapat membantu untuk memahami perubahan yang diajukan.

**Comment by mychaelgo** [comment]
Oh media di sini maksudnya kayak detik, kompas gitu? Sumber berita nya ya? Kalau seperti itu, saya rasa udh ok :)

**Comment by bobbypriam** [comment]
@mychaelgo Yap, betul mas 👍

**Comment by bobbypriam** [comment]
Mungkin pertanyaan yang harus dijawab adalah:
1. Apakah endpoint dan informasi yang disediakan masuk akal dan mencakup use case yang dibutuhkan?
2. Apakah struktur response yang disediakan masuk akal?

Saya pribadi masih galau di:
- `*/media-sentiments` (3 dan 6)<br>Apakah keterangan media sudah cukup? Atau kita dump saja semua property dari media di objectnya?
- News `mentions` (7 dan 8)<br>Sama, apakah keterangan candidate sudah cukup?
- `/media/{id}/sentiments` (11)<br>Idem untuk data pairing.

Edit: oke, akhirnya saya menyelesaikan poin-poin di atas dengan mengubah endpoint untuk menginclude datanya agar lebih fleksibel.

**Comment by bobbypriam** [comment]
Spesifikasi v0.2 sudah dibuat dan dapat [dilihat di sini](https://rawgit.com/bobbypriambodo/rojak/feature/rojak-api/spec-v0.2/rojak-api/spec/api-spec.html) (PR #115). Mohon reviewnya 🙇

**Comment by pyk** [comment]
mantap @bobbypriambodo 👍

**Comment by bobbypriam** [comment]
#115 sudah merged, kalau tim UI ada request perubahan silakan buat issue baru aja ya. Sekarang kita akan coba bikin implementasinya.
