### ISSUE TITLE
[rojak-api] Ubah spec query params untuk embed, media_id, dan candidate_id menjadi array

### ISSUE THREAD

**Issue by bobbypriam** [pyk/rojak#122]
Spesifikasi untuk query params tersebut saat ini tidak standar. Proposal penggantian:
### `embed`

```
// Old
?embed=field1,field2

// New
?embed[]=field1&embed[]=field2
```
### `media_id` (also for `candidate_id`)

```
// Old, doesn't work
?media_id=1&media_id=2

// New
?media_id[]=1&media_id[]=2
```

Revisi ini akan memudahkan implementasi dan cukup standar sehingga banyak disupport out of the box oleh library (misalnya Retrofit).

**Comment by pyk** [comment]
Fixed by #124
