### ISSUE TITLE
[rojak-database] Update schema ke v0.1

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#14]
Yang pertama, kita perlu informasi suatu sentiment untuk siapa. Jadi table [`sentiment`](https://github.com/pyk/rojak/blob/master/rojak-database/mysql_tables.sql#L33) kita tambahi foreign key ke candidate. Sama perlu column `score` di tabel news_sentiment, buat nyimpen score probability nya

Yang kedua, kita perlu menyimpan informasi cagub siapa aja yang di mention dalam suatu berita. Jadi kita bikin table join baru untuk menghubungkan `news` dengan `candidate`. 

```
nama table: mention
column:
news_id
candidate_id
inserted_at
updated_at
```

Yang ketiga, kita perlu rename `candidates` ke `candidate` supaya sama dengan nama table lain. 
Lalu karena yg di mention oleh berita itu bisa satu orang saja, table `candidate` kita buat untuk menyimpan data satu orang aja cagub/cawagub. 

Lalu untuk menyimpan data pasangan calon kita buat table baru untuk menyimpan data pasangan calon: `pair_of_candidates`

**Comment by bobbypriam** [comment]
Tabel `sentiment` itu nanti isinya seperti apa ya? Dia ada name, `id` dari kandidat, dan skor, berarti tiap row sentimen akan mewakili:
- Sentimen positif untuk cagub A
- Sentimen negatif untuk cagub A
- Sentimen netral untuk cagub A
- Sentimen positif untuk cagub B
- dst.

atau gimana?

Basically saya agak bingung relasi datanya sih 😄  Ada relasi `news_sentiment` antara `news` dan `sentiment`, ada relasi `mention` untuk `news` dan `candidate`, tapi ada juga relasi pada `sentiment` antara dia dan `candidate`. Kok jadi kayak dobel-dobel gitu...

**Comment by pyk** [comment]
Yup bener mas, terus ralat mas untuk `score` nya nanti di table [`news_sentiment`](https://github.com/pyk/rojak/pull/18/files#diff-a0e804fc4abba5e9c2fe63dbc491a0f8R90).

Kasarannya: Jadi nanti tiap news ada seberapa persen dia positif ke cagub A. Bukan "exactly" positif.

> Basically saya agak bingung relasi datanya sih 😄 Ada relasi news_sentiment antara news dan sentiment, ada relasi mention untuk news dan candidate, tapi ada juga relasi pada sentiment antara dia dan candidate. Kok jadi kayak dobel-dobel gitu...

`news_sentiment` untuk nyimpen informasi suatu berita punya sentiment apa
`mention` untuk nyimpan informasi suatu berita mention candidate siapa aja
`sentiment` dan `candidate` untuk nyimpen informasi sentiment untuk candidate yg mana. contoh `pro_anies` sentiment ini untuk candidate `anies`

**Comment by pyk** [comment]
Resolved by #18
