### ISSUE TITLE
Rojak Deployments

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#142]
Team, disini kita diskusikan tentang deployment nya Rojak ya

Yang pertama untuk DNS nya kita bisa pake:
- https://rojak.artificialintelligence.id untuk `rojak-ui-web`
- https://rojak-api.artificialintelligence.id untuk `rojak-api`
- https://rojak-database.artificialintelligence.id untuk `rojak-database`

Btw karena ada promo domain `.id`, apa aku perlu purchase `rojak.id` ya? 😄 

Terus untuk infranya, nanti mungkin tiap-tiap tim ada perwakilan yang mau jelasin apa aja requirementnya.

Untuk requirement `tim-data`:
- `rojak-pantau` kita pake droplet [DigitalOcean](https://m.do.co/c/ddb6db36549a) (DO referral 😄 )
- `rojak-database` kita manage sql sendiri juga di droplet DO
- `rojak-analyzer` juga di droplet DO

Infra `tim-data` sudah running dari ~24 hari yang lalu. So far looks good.

Nah untuk `tim-ui`, `tim-api` dan `tim-app` mungkin bisa jelain kira2 apa aja ya requirementnya untuk deploy masing-masing komponen?

Untuk `tim-ui`, apakah static server bisa ya? (Misal pake github page)
Untuk `tim-api` nanti pasti butuh server juga, kira2 spec yang minimum gimana ya?
Untuk `tim-app` nanti sharing appsnya gimana ya?

Mungkin itu sih, feel free untuk nambahin kalo ada yang kelewatan 🙇 🙇

**Comment by mychaelgo** [comment]
Tim apps: untuk sharing apps bisa menggunakan hockeyapps atau beta dari fabric? (saya lebih prefer fabric karena udah lengkap dgn analytics dan crash reporting)
Atau yang lain ada usul? :)

**Comment by haydarai** [comment]
Sharing app itu maksudnya buat beta test ya? Kalau dari Google Play sendiri ada fitur buat alpha/beta test
https://support.google.com/googleplay/android-developer/answer/3131213?hl=en

Untuk akun Google Playnya nanti pakai apa?

**Comment by mychaelgo** [comment]
@haydarai  iy harusnya yang dimaksud adalah sharing app buat beta test

**Comment by haydarai** [comment]
@mychaelgo Ngikut aja deh kayaknya, selama ini baik analytics, crash reporting, maupun sharing app biasanya pake solusi dari Google Play. Kalau ada yang pernah pake yang lain dan ternyata lebih enak ya boleh juga

**Comment by bobbypriam** [comment]
+1 `rojak.id`, lebih gampang diketik 😄 

Untuk `rojak-api`, dari requirement kita harusnya butuh sebuah server yang udah diinstall Docker Engine.

Untuk spec minimum, saya ingin percaya bahwa API saat ini bisa berjalan lancar di Droplet DO yang $5, but I don't want to be overconfident 😅 . Intinya komponen dari API cuma sebuah docker image berisi aplikasi Phoenix yang komunikasi dengan `rojak-database`, jadi sepertinya kita ga butuh storage yang besar. Untuk aplikasinya sendiri saya pikir bisa jalan dengan memori < 100MB asal ga ada leak. Single core juga ga masalah sepertinya. Mungkin yang butuh diperhatikan itu bandwidth sih ya. Tapi semua ini harus profiling dulu sih.

Kita bisa dapet satu server dulu untuk nyoba ga ya @pyk?

**Comment by pyk** [comment]
https://rojak.id purchased 👌 , tinggal mengurus dokumen ktp dkk hehe

Jadi untuk DNS kita bisa pake:
- https://rojak.id untuk rojak-ui-web
- https://api.rojak.id untuk rojak-api
- https://db.rojak.id untuk rojak-database

> Untuk akun Google Playnya nanti pakai apa?

@haydarai Wah kalo akun google play aku pribadi belum punya mas, kira2 disini ada yg bersedia upload di gogle playnya gak ya? Kalo pake selain google play juga boleh sih mas

@bobbypriambodo aku setup droplet yg docker ya 🙇 , nanti crednya aku kirim via slack

**Comment by girikuncoro** [comment]
btw ini ga ada operational cost sama sekali ya? kalo ada yang perlu patungan ane siap menyumbang

**Comment by pyk** [comment]
@girikuncoro untuk operational costnya, luckily, yg untuk tim data masih muat di satu mesin 1GB mas haha. `rojak-pantau` sama `rojak-analyzer` jalannya cuma periodically. (`rojak-analyzer` belum di prod btw)

Untuk sekarang infra kita:

<img width="1034" alt="screen_shot_2016-10-28_at_9_52_38_am" src="https://cloud.githubusercontent.com/assets/2213646/19793012/a1640c06-9cf4-11e6-90a6-50363d132780.png">

Yg butuhin resource banyak nanti itu `rojak-pantau` (semakin banyak media yg di pantau). 

Hmm kalau patungan uang rada susah sih mas. Mungkin yang punya instance VM bisa bantu buat running `rojak-pantau` kali ya kalau medianya makin banyak, untuk jumlah media yg sekarang masih bisa handle sih.

**Comment by rawgni** [comment]
@pyk kalau rojak-pantau kan ga jalan 24 jam, gimana kalo dipindah ke heroku atau free service lain nya. basically scrape, process then store in db (db nya tetap di rojak.id).

**Comment by pyk** [comment]
@rawgni ide bagus mas, jadi kita tinggal trigger gitu ya endpoint nya? 

misal:

```
GET /scrape?media=detikcom
```

dia langsung run `spider` detikcom?

**Comment by rawgni** [comment]
@pyk mungkin dengan cron atau [scheduler](https://devcenter.heroku.com/articles/scheduler) ?

seberapa besar resource yg dibutuhkan `rojak-pantau` (mem atau cpu cycle)?

**Comment by girikuncoro** [comment]
cuma kalo heroku free dyno itu bukannya sleep tiap 6 jam ya? ah tapi kalo ga perlu real time2 amat ga masalah

**Comment by pyk** [comment]
> @pyk mungkin dengan cron atau scheduler ?

@rawgni wah ide bagus mas 👍 

oh ya untuk API nya udah di deploy ya:
- Rojak API https://api.rojak.id/

Tinggal nunggu temen2 FE ini gimana ya deploynya? untuk sementara ini https://rojak.id aku point ke repo ini

**Comment by pyk** [comment]
Ini kita close ya, udah reach milestone `Rojak v1.0.0`. next step, kita akan diskusi tentang `Rojak v2.0.0`, mostly penyempurnaan aja.
