### ISSUE TITLE
[rojak-database] Lengkapi data pasangan cagub-cawagub

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#146]
Kalau kita lihat disini https://api.rojak.id/v1/pairings

Ada beberapa data yg masih kurang lengkap, contoh nya website dari pasangan anies-sandi.

Kalian bisa nambahin datanya lewat disini untuk data yg kurang https://github.com/pyk/rojak/blob/master/rojak-database/data_pasangan_cagub_cawagub.json

Feel free to send PR! 🙇

**Comment by rawgni** [comment]
untuk anies sandi, yang ini bukan ? @pyk 
![dp bbm maju bersama anies sandi 2](https://cloud.githubusercontent.com/assets/11707733/19830992/edde0632-9e29-11e6-9fc3-68f79bfc2f9c.jpg)

http://jakartamajubersama.com/
https://www.instagram.com/gubernurdki2017/

**Comment by girikuncoro** [comment]
Ini instagramnya agus sylvi: https://www.instagram.com/agus.sylvi/

@rawgni lengkap tuh anies sandi twitter sama fb page nya juga:
https://www.facebook.com/jakartamajubersama
https://twitter.com/jktmajubersama

btw kayanya perlu tambah link youtube juga ya di field?
https://www.youtube.com/channel/UCBokEPnuBE1dW5B991CLwEA

**Comment by pyk** [comment]
> btw kayanya perlu tambah link youtube juga ya di field?

Wah bener juga mas, kalo lengkap semua boleh sih. Pas dulu aku cari yang udah punya ahok sama anies aja

**Comment by pyk** [comment]
btw fixed by #152 🙇
