### ISSUE TITLE
[rojak-api] Setup Dockerfile untuk deployment

### ISSUE THREAD

**Issue by bobbypriam** [pyk/rojak#15]
Karena kita ingin menggunakan Docker untuk deployment, butuh dibuat Dockerfile untuk building production image. Dari yang saya baca, ada dua approach untuk melakukan deployment sebuah Phoenix app. Akan dibahas mengenai masing-masing approach, lalu kita akan melihat pros dan cons-nya.
## The basic Phoenix way

Pada dokumentasinya, Phoenix memberikan [arahan mengenai proses deployment sebuah aplikasi](http://www.phoenixframework.org/docs/deployment). It boils down to:
1. set env var `MIX_ENV=prod`
2. melakukan kompilasi menggunakan perintah `mix compile`
3. menjalankan server dengan `mix phoenix.server`
## The Elixir OTP release way

Karena Elixir adalah bahasa yang compiled (seperti Go, Java, dsb.), maka logis jika distribusi aplikasi untuk production hanya melibatkan compiled binary-nya saja. Dengan tools seperti [exrm](https://github.com/bitwalker/exrm) dan [Distillery](https://github.com/bitwalker/distillery), proses ini dapat berjalan dengan mudah. Binary yang dihasilkan sudah mencakup ERTS (Erlang Run Time System) sehingga pada container deployment tidak ada dependency pada Erlang dan Elixir. Dokumentasi Phoenix juga memberikan [arahan untuk deployment menggunakan releases](http://www.phoenixframework.org/docs/advanced-deployment). Metode ini juga lebih support app versioning.

Stepnya adalah:
1. Install exrm atau Distillery sebagai dependency
2. Jalankan `MIX_ENV=prod mix release` untuk meng-compile menjadi binary
3. Binary siap dijalankan, berada di direktori `rel/`

Caveat dari metode ini adalah kompilasi harus dilakukan pada host dengan OS dan arsitektur sama dengan host production, karena ERTS yang dibundle dalam binary aplikasinya diambil saat kompilasi release. Atau kita bisa tidak membundle ERTS sama sekali dan menggunakan apa yang ada di container deployment, tapi artinya ada dependency dengan Erlang dan [mungkin saja ada beberapa isu lain](https://github.com/phoenixframework/phoenix_guides/issues/254#issuecomment-125252519).
## Comparison

(Ini sotoyan saya, berdasarkan baca-baca. Kayaknya ga ada artikel yang bener-bener ngebandingin keduanya 😄 )

Dari sisi pembuatan Dockerfile, untuk basic Phoenix way:
- **pros:**<br />Straightforward, easy to set up
- **cons:**<br />Image will depend on Erlang and Elixir, yang artinya size image-nya besar; ada source code dalam image (yang excessive, karena compiled)

Sementara untuk Elixir release:
- **pros:**<br />Tidak ada dependency, hanya taruh binary dan jalankan, sehingga image size bisa dioptimisasi; tidak ada kode di image hasil
- **cons:**<br />Setup not so trivial; ada beberapa konfigurasi pada Phoenix yang harus ditambahkan; harus memastikan binary hasil kompilasi berjalan di image untuk deployment (`mix release` bisa dijalankan di docker container juga untuk bisa dapat arsitektur yang sesuai sih)
## Jadi, yang mana?

Masih butuh main-main lagi 😄  Kalo saya sendiri, saat ini sepertinya opsi Elixir release lebih favorable dari sisi versioning dan image size (dan kebanyakan artikel mengenai Docker Phoenix Deployment menggunakan exrm sehingga sepertinya cukup tested, saya tidak menemukan yang menggunakan basic Phoenix way selain di dokumentasi Phoenix sendiri). Kalau ada cara yang mungkin lebih baik kita bahas di issue ini.

**Comment by pyk** [comment]
@bobbypriambodo setuju dengan yg the elixir way, kita tinggal jalanin binary nya dengan docker image yg lebih kecil size nya

**Comment by bobbypriam** [comment]
Oke, hasil dari main-main dengan opsi pakai release dan Distillery, ada beberapa hal yang harus di-note.
1. <del>Sepertinya saya salah mengerti mengenai metode Elixir/OTP release; executable yang dihasilkan ternyata tetep dependent sama Erlang (which kinda makes sense, karena Erlang berjalan di atas Erlang VM. Jadinya analog dengan gimana kita harus punya Java untuk ngejalanin file .jar). Still feels kind of weird though, saya lagi nanya-nanya di slack Elixir tentang ini.</del> Nevermind, ternyata bisa tanpa dependensi Erlang. Woohoo!
2. Untuk image deployment sepertinya kita akan menggunakan image yang berbasis Alpine Linux, seperti [yang sedang banyak dilakukan](https://www.brianchristner.io/docker-is-moving-to-alpine-linux/). Alasannya adalah Alpine memiliki size yang jauh lebih kecil dibanding misalnya menggunakan image basis Debian atau Ubuntu (5MB Alpine vs 188MB Ubuntu).
3. Karena target tujuan adalah Alpine, maka kompilasi release juga harus dilakukan pada arsitektur Alpine. Untungnya, sudah tersedia image untuk Erlang/Elixir berbasis Alpine [oleh msaraiva](https://github.com/msaraiva/alpine-erlang). Kita akan menggunakan itu untuk kompilasi release.

PR on the way.

**Comment by bobbypriam** [comment]
Solved with #23.
