### ISSUE TITLE
[rojak-pantau] Pantau tirto.id

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#150]
Ada beberapa topik yang bisa kita pantau dari media ini:
- https://tirto.id/q/pilkada-dki-jakarta-k6
- https://tirto.id/q/pilkada-dki-jakarta-2017-cmJ
- https://tirto.id/q/pilkada-dki-pw
- https://tirto.id/q/pemilihan-gubernur-dki-jakarta-n4

Catatannya:

Untuk `raw_content` kita harus remove noise berita terkait yang ada di artikelnya misal:

```
<strong>Reporter :</strong> Arlian Buana            <br>
<strong>Laporan 1 : </strong>Agus Harimurti Yudhoyono Si Peselancar Politik<br><strong>Laporan 2 : </strong><a href="//tirto.id/kejayaan-dan-kejatuhan-mulut-ahok-bYV9" class="link-bold">Kejayaan dan Kejatuhan Mulut Ahok </a><br><strong>Laporan 3 : </strong><a href="//tirto.id/anies-baswedan-akhirnya-benar-benar-turun-gunung-bYWa" class="link-bold">Anies Baswedan Akhirnya Benar-Benar Turun Gunung </a><br><strong>Laporan 4 : </strong><a href="//tirto.id/cuma-ahok-yang-punya-tendensi-berseberangan-bYWc" class="link-bold">"Cuma Ahok yang Punya Tendensi Berseberangan" </a><br>
```

Solusi paling naive mungkin kita ambil nama reporter/author nya lalu kita temove content setelahnya

Feel free to send PR! 🙇

**Comment by rawgni** [comment]
@pyk untuk artikel yang tidak ada tanggal nya gimana yah ?
contoh: https://tirto.id/anies-baswedan-akhirnya-benar-benar-turun-gunung-bYWa

**Comment by pyk** [comment]
@rawgni kalau gak ada tanggalnya skip aja mas (otomatis udah ke drop kalau gagal ambil `date` selector)
