### ISSUE TITLE
[rojak-pantau] Pantau arah.com

### ISSUE THREAD

**Issue by rawgni** [pyk/rojak#151]
http://pilkada.arah.com/berita
http://pilkada.arah.com/sosmed
http://pilkada.arah.com/pendukung/detail/provinsi/DKI%20JAKARTA
http://www.arah.com/tags/19997/Anies-Baswedan.html

Bagaimana dengan site ini ? @pyk

**Comment by pyk** [comment]
Looks good mas 👌
