### ISSUE TITLE
[rojak-api] Draft API design

### ISSUE THREAD

**Issue by bobbypriam** [pyk/rojak#16]
Requirement dasar dari API bisa dilihat pada [#4 (comment)](https://github.com/pyk/rojak/issues/4#issuecomment-251369566). Issue ini untuk diskusi API design dari rojak-api.

**Comment by pyk** [comment]
@bobbypriambodo (copas diskusi slack mu di #general):

```

bobby [10:37 PM]  
Soal mockup API, deliverable yang diharapkan apa ya? Soalnya kita agak bingung nih data yang dibutuhkan dari rojak-ui-* apa aja.

Flownya enakan mana ya:
1. Tim UI bikin mockup dari masing-masing dan ngelist datanya apa yang dibutuhkan -> Tim API bikinin endpointnya, atau
2. Tim API bikin RESTful endpoints untuk semua entity yang ada (candidate, media, news, sentiment) -> terserah Tim UI mau pakenya kayak apa

Mungkin diskusinya bisa di sini atau di https://github.com/pyk/rojak/issues/16
```

Mending yg No 2, soalnya API nya bisa di buat orang luar juga yg pengen pake datanya. Misal messenger bot (https://github.com/pyk/rojak/issues/7#issuecomment-251297005) dll

**Comment by rrmdn** [comment]
No 2 make sense, no 1 nanti malah banyak yg gak sesuai kalo bikin mockup dulu, lebih susah sync.

**Comment by vck** [comment]
no 2 :smile:

**Comment by bobbypriam** [comment]
I see, oke berarti kita akan coba rampungin spec-nya dulu ya. Tapi harusnya sih cukup sederhana:

```
- /:resourceType                      // dapetin list of :resourceType, misalnya /candidates
- /:resourceType/:id                  // dapetin :resourceType dengan identifier tertentu
- /:resourceType/:id/:relatedResource // dapetin relatedResource untuk resource tertentu (misalnya /news/1/candidates)
```

dsb. Bisa dibikin ad-hoc endpoint juga kalau dibutuhkan.

Kita akan ngasih beberapa query param juga (misalnya `embed`, `sort`, `filter`, `fields`, untuk pagination, dll). Operasinya hanya akan ada `GET`. Sukses atau error akan ditandai dengan HTTP status code (200 success, 4xx/5xx error mungkin dengan payload error code spesifik).

Apakah kira-kira cukup reasonable? Mungkin dengan info ini bisa sedikit-sedikit ngebantu tim UI bikin mockup 😄

**Comment by bobbypriam** [comment]
Mas @fajarmf mau ambil yang ini? Saya kayaknya mau ngoprek #15 dulu hehe.

**Comment by fajarmf** [comment]
First draft on #22

**Comment by fajarmf** [comment]
#22 merged, tapi tetep bergerak ya. nanti di update lagi.

Btw, untuk lihat list of models dan attributes nya ada dimana ya? @bobbypriambodo @pyk ?

**Comment by pyk** [comment]
@fajarmf untuk model phoenix nya disini mas https://github.com/pyk/rojak/pull/27, belum di merge.

Untuk models dan attributes di database ada di https://github.com/pyk/rojak/blob/master/rojak-database/rojak_schema_latest.sql

**Comment by bobbypriam** [comment]
Draft API dilanjutkan lagi di #36. Coba lihat apakah ada use case yang masih ketinggalan.

**Comment by bobbypriam** [comment]
#36 sudah dimerge, namun ada beberapa concern untuk revisi, seperti ada pada #106. Isu ini akan ditutup agar diskusi bisa pindah ke sana.
