### ISSUE TITLE
[rojak-api] Buat Phoenix Models berdasarkan Schema Data

### ISSUE THREAD

**Issue by bobbypriam** [pyk/rojak#17]
Dengan skema data yang ada pada #2, kita harusnya sudah bisa mulai setup models untuk digunakan dalam aplikasi Phoenix kita. Skema ini masih moving target, tapi beberapa elemen sepertinya (candidates, media, news, sentiment) sudah reasonable untuk di-implement.

Yang perlu diperhatikan: kita tidak perlu berurusan dengan migration. Kita akan menggunakan eksternal database sehingga yang perlu dilakukan hanyalah mapping dari Schema menjadi Model.

Autogeneration untuk Model tanpa Migration bisa dilakukan dengan:

```
$ docker-compose run --rm web mix phoenix.gen.model [ModelName] [table_name] [property1:type1 property2:type2 ...] --no-migration
```

Misalnya

```
$ docker-compose run --rm web mix phoenix.gen.model User users name:string age:integer --no-migration
```

Referensi untuk `phoenix.gen.model`: [Lihat dokumentasi](https://hexdocs.pm/phoenix/Mix.Tasks.Phoenix.Gen.Model.html)
Referensi untuk Model pada Phoenix:  [Lihat dokumentasi](http://www.phoenixframework.org/docs/ecto-models)

**Comment by pyk** [comment]
aku akan buat model ini sesuai #18 , ada beberapa generator yg harus di update dulu

**Comment by pyk** [comment]
Wah yg rada ribet relasinya sih ini hehe https://hexdocs.pm/ecto/Ecto.Schema.html

Baca2 dulu

**Comment by pyk** [comment]
@bobbypriambodo btw untuk test modelnya gak bisa lewat docker container, soalnya `Ecto` butuh `mysql(1)` di host untuk running 

```
(rojak) % docker-compose run --rm web mix test test/models/candidate_test.exs 
Compiling 11 files (.ex)
Generated rojak_api app
** (RuntimeError) could not find executable `mysql` in path, please guarantee it is available before running ecto commands
    lib/ecto/adapters/mysql.ex:291: Ecto.Adapters.MySQL.run_with_cmd/3
    lib/ecto/adapters/mysql.ex:139: Ecto.Adapters.MySQL.storage_up/1
    lib/mix/tasks/ecto.create.ex:36: anonymous fn/3 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:328: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:261: Mix.Task.run/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

Untuk model generatornya udah Oke. Using params `-e "MIX_ENV=test"`also return the same error.

Any ideas?

**Comment by bobbypriam** [comment]
Hmm, interesting. Tampaknya `mix test` secara default akan selalu melakukan setup test database biarpun sebenernya testnya unit. Naive solution bisa install mysql di `Dockerfile.dev`. I'll look into it.

**Comment by bobbypriam** [comment]
Oke, jadi alasan kenapa itu terjadi adalah karena perintah `mix test` di-alias untuk ngerun setup database.

File `mix.exs`:

``` elixir
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"],
     "test": ["ecto.create --quiet", "ecto.migrate", "test"]]
  end
```

Ecto komplain ketika perintah `ecto.create` karena ga ada `mysql`. Actually, kita kan ga akan butuh create database dan migrate, apa hapus aja ya alias untuk `"test"` itu? Barusan coba ngehapus alias tersebut, ngejalanin dengan

```
$ docker-compose run --rm --no-deps -e MIX_ENV=test web mix test
```

dan berhasil.

Ini juga berarti kita akan menggunakan database yang sama untuk testing dan dev melalui env variable `DB_NAME=rojak_database` di `docker-compose.yml` (which seems okay, karena operasi kita cuma `GET`). Ada tanggapan @pyk?

**Comment by pyk** [comment]
@bobbypriambodo sebenernya tujuanku untuk run test itu untuk make sure model yang di generate udah bener sih (sesuai schema di existing database). Apa ada cara lain ya selain test via `mix test`?

Pernah lihat REPL nya elixir tapi belum nyoba. Apa bisa buat coba-coba modelnya ya? Seperti run query sederhana gitu misalnya untuk make sure definisi modelnya udah tepat

**Comment by bobbypriam** [comment]
Coba klarifikasi dulu ya, ini maksudnya kita sebelumnya udah ngemigrate dan generate data di-database kan ya? Jadi kita punya dummy database yang jalan beserta datanya, kita udah buat modelnya, dan mas mau ngetes apakah modelnya itu sesuai atau ngga?

Kalo gitu, untuk ngetes manual iya bisa pakai REPL.

```
$ docker-compose run --rm web iex -S mix
```

^ Itu bakal compile source kita dan ngejalanin IEx (Interactive Elixir). Setelah ada di IEx, untuk ngetes query `SELECT` bisa kayak gini:

``` elixir
iex(1)> alias RojakAPI.Repo
RojakAPI.Repo
iex(1)> alias RojakAPI.Candidate
RojakAPI.Candidate
iex(1)> Repo.all(Candidate)  # SELECT (fields) FROM `candidates`
```

di mana `(fields)` akan sesuai dengan definisi schema di model kita. Kita juga bisa select per id:

``` elixir
iex(1)> Repo.get!(Candidate, id)  # SELECT (fields) FROM `candidates` where `id`=id
```

Kita juga bisa ngequery relationship yang ada dengan `Repo.preload`, contohnya:

``` elixir
iex(1)> Candidate |> Repo.all |> Repo.preload([:news])
iex(1)> Candidate |> Repo.get!(id) |> Repo.preload([:news])
```

Apakah membantu?

**Comment by pyk** [comment]
@bobbypriambodo thanks mas! saya coba dulu 👍

**Comment by pyk** [comment]
untuk progressnya bisa dilihat di #27

**Comment by bobbypriam** [comment]
Solved di #27.
