### ISSUE TITLE
[rojak-pantau] Pantau NUSANEWS.com

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#174]
Nemu media ini dari facebook feed (duh makin banyak berita2 panas pilkada haha 😂 )

Topik yang bisa kita pantau dari media ini:

* http://www.nusanews.com/search/label/Pilkada

Feel free to send PR 🙇

**Comment by rawgni** [comment]
ketemu ini bro :( `http://internetpositif.uzone.id/page.block`

**Comment by pyk** [comment]
@rawgni woah, ISP apa mas? aku pake `smartfr*n` bisa di akses kok

**Comment by rawgni** [comment]
@pyk `indih*me` mas

**Comment by pyk** [comment]
@rawgni dia di blokir ternyata gara2 ada Demo itu mas http://teknologi.news.viva.co.id/news/read/843161-demo-4-november-bin-dan-polri-minta-11-situs-ini-diblokir 😱
