### ISSUE TITLE
[rojak-database] Perubahan schema sentiment

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#175]
Kita akan merubah skema sentiment kita. Sebelumnya `candidate_id` sekarang jadi `candidate_pair_id`, karena sentiment nya toward ke pasangan bukan perorangan.

Diskusinya bisa diliat di https://github.com/pyk/rojak/issues/128#issuecomment-258112292 atau di [#tim-data](https://rojakteam.slack.com/archives/tim-data/p1477982208000098)

Untuk daftar sentiment yang kita pakai:

```
pos_agus_sylvi
neg_agus_sylvi
pos_ahok_djarot
neg_ahok_djarot
pos_anies_sandi
neg_anies_sandi
oot
```

**Comment by pyk** [comment]
I will tackle this tomorrow

**Comment by bobbypriam** [comment]
Berarti dengan ini kita ga bisa query sentimen terhadap satu orang aja ya? Apa mending endpoint `/candidates*?embed[]=sentiments` dan `/candidates/1/media-sentiments` dihapus aja?

**Comment by pyk** [comment]
> Berarti dengan ini kita ga bisa query sentimen terhadap satu orang aja ya? 

@bobbypriambodo iya mas

Btw ini fixed by #178 yah, di prod udah di upgrade juga ke `v0.5` 🙇
