### ISSUE TITLE
[rojak-analyzer] Training data

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#19]
Untuk `rojak-analyer` kita mau tackle this problem:

```
“Given a text news, we want to find the sentiment of the news against the candidate”
Dimana sentiment nya: {pro_ahok, pro_anies, pro_agus, con_ahok, etc}
dan satu berita bisa punya lebih dari satu sentiment
```

Tujuannya udah jelas, untuk bisa capai itu ada beberapa step yang harus kita lakuin:
1. Kumpulin training data (berita beserta label sentimen nya)
2. Buat model menggunakan metode tertentu dan benchmark metodenya menurut beberapa metric seperti akurasi dll

Masalah yang kita mau diskusiin sekarang

Bagaimana mengumpulkan training datanya? 
Bagaimana mengumpulkan data training secara tim?

Naive approach will be setup google spreadsheet for this 😄

**Comment by Teofebano19** [comment]
@pyk : Bay, kalo yang ngumpulin via google spreadsheet itu maksudnya hasil scrap kita copas semua di dalam spreadsheet? Kalo dibikin database dengan format yang sama nanti tinggal import2 gitu gimana? Jadi kita labelling dari sana lebih enak.

**Comment by hayyuelha** [comment]
@Teofebano19 labelling di database Te? Bukannya lebih enak kalo labelling di spreadsheet ya...? Aku ngebayanginnya nanti hasil scrape tuh disimpen dalam format csv, jadi kan bisa gampang dibuka di spreadsheet

**Comment by pyk** [comment]
@Teofebano19 setuju sama @hayyuelha, nanti bisa disimpen di database dulu baru di export ke CSV, nah dari file CSV bisa di import via spreadsheet

**Comment by pyk** [comment]
Training datanya sudah ada di google spreadsheet yah cek email masing2 untuk tim data. Bagi kalian yg pake semi-supervised method bisa langsung buat modelnya 🙇

**Comment by girikuncoro** [comment]
Btw ini data newsnya kan ribuan yah (beritasatu aja gw set 600 news buat collect dari akhir juli 2016 sampe sekarang), ga mau dicrowdsource/mechanical turk aja buat labeling sentimennya? Ga tau tapi biasanya ada yang reliable gak yah

**Comment by pyk** [comment]
>  ga mau dicrowdsource/mechanical turk aja buat labeling sentimennya? Ga tau tapi biasanya ada yang reliable gak yah

@girikuncoro semi-manual keknya udah cukup mas, train->predict->koreksi->train gitu hehe

Guys, data labelling terbaru udah ada di channel #tim-data ya. Ini aku close dulu 🙇
