### ISSUE TITLE
Schema Data

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#2]
Schema data akan mengikuti informasi apa yang mau kita simpan. Ini gak fix disini sih, schema data akan berubah-ubah sesuai informasi apa yang mau kita simpan.

Untuk sekarang v0.0 informasi yang kita simpan adalah:
1. Informasi semua pasangan cagub-cawagub
2. Informasi semua media daring di Indonesia
3. Informasi semua berita yang membahas tentang Pilkada DKI Jakarta 2017

Jadi untuk sementara ini schema datanya seperti ini #9 yuk mari kita diskusikan!

**Comment by Teofebano19** [comment]
@pyk : punten Bay. Mau nanya untuk tabel kandidat, itu penyimpanan data nama gimana formatnya? Apakah hanya ngikut nama Cagub aja? atau Cagub-Cawagub?

**Comment by bobbypriam** [comment]
Thanks!

Questions, though: Apakah semua entity itu perlu dibuatkan endpointnya? How would we want the data to be queried?

**Comment by pyk** [comment]
@Teofebano19 Untuk sekarang data dummny nya `cagub - cawagub` mas, btw apa perlu di pisah ya cagub sendiri cawagub sendiri?

**Comment by pyk** [comment]
@bobbypriambodo Nah itu yg kemaren aku mau diskusikan mas. Menurut temen2 UI gimana nih @vickydasta @riordhn @rromadhoni ?

**Comment by vck** [comment]
@pyk _to simplified things_, enaknya digabung saja. atau ada yang saya lewatkan?

**Comment by pyk** [comment]
@vickydasta maksutnya di gabung kaya gimana?

**Comment by pyk** [comment]
Team, regarding https://github.com/pyk/rojak/issues/4#issuecomment-251369566 we need to update the schema.

Updatenya:
1. Relasi `sentiment` dan `candidate` (sentiment ini untuk candidate siapa)
2. Relasi `news` dan `candidate` (satu berita bisa mention banyak candidate)

Will push this on the Schema v0.1

**Comment by pyk** [comment]
Schema data kita udah versi V0.4 yah #34
