### ISSUE TITLE
Rojak UI Web

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#3]
Mas @rromadhoni mungkin bisa memberikan brief disini nanti Rojak UI Web nya seperti apa (Stack, requirement dll).

**Comment by rrmdn** [comment]
## Stack

Stack berikut menurut saya hampir memenuhi kebutuhan kita untuk UI: scalable, lightweight, predictable, fast rendering.
1. React (UI Library)
2. React Router (Routing library)
3. Redux (State management)
4. UIKit CSS (CSS Framework)

Targetnya build file tidak lebih dari 200KB
Open suggestion

**Comment by adrianha** [comment]
Untuk CSS frameworkny menggunakan bulma.io gimana mas @rromadhoni ? sepertinya lebih ringan, soalny dia pure only css..

**Comment by santosoide** [comment]
Boleh tuh mas @rromadhoni pakai Material Design Lite

**Comment by pyk** [comment]
Ini kita close ya, udah reach milestone `Rojak v1.0.0`. next step, kita akan diskusi tentang `Rojak v2.0.0`, mostly penyempurnaan aja.
