### ISSUE TITLE
[rojak-pantau] pipeline issue?

### ISSUE THREAD

**Issue by girikuncoro** [pyk/rojak#44]
Apakah ini maksudnya `spider.slack` di line 31?
https://github.com/pyk/rojak/blob/master/rojak-pantau/rojak_pantau/pipelines.py#L31

Soalnya gw secara ga sengaja dapet db error lalu kena di catch nya `pipeline.py` tapi dapet:

```
AttributeError: 'SaveToMySQL' object has no attribute 'is_slack'
```

**Comment by pyk** [comment]
@girikuncoro ah ya, itu harusnya `spider.is_slack`. Bentar aku fix ya

**Comment by pyk** [comment]
oke fixnya udah di merged #46 , thanks untuk reportnya mas 🙇

**Comment by girikuncoro** [comment]
@pyk sama 1 lagi sbnernya coba cek komen ku di sini https://github.com/pyk/rojak/pull/43/files/54acfc07c45a94a37a785d4c5fd1678af88a04e2

Abaikan kalo bukan issue :D

**Comment by pyk** [comment]
@girikuncoro eh komen masnya kok gak ada ya?

**Comment by pyk** [comment]
keknya github reviewnya belum kamu publish mas

**Comment by girikuncoro** [comment]
iya sepertinya belum terpublish tadi :D
