### ISSUE TITLE
Rojak Data

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#5]
Disini akan dijelaskan gambaran besar apa yang Tim Data bisa kontribusikan untuk Project Rojak.

Mainly kita akan kontribusi ke `rojak-database`, `rojak-pantau` dan `rojak-analyzer`. Feel free untuk fokus ke salah satu atau lebih dari satu. 

Hal pertama yang harus kita lakuin adalah menentukan schema database. Hal ini di perlukan agar Tim API bisa membuat mockup API nya, kemudian Tim UI bisa menggunakan mockup API nya untuk memulai development. Hal ini kita diskusikan lebih lanjut di #2 

Hal kedua adalah `rojak-pantau` dan `rojak-analyzer`. Untuk `rojak-pantau` kita akan diskusikan stack apa yang kita pakai, kita juga bisa menggunakan stack kita sebelumnya di Sayoeti AI. Jadi kita tinggal improve aja dan menambah banyak media lagi. Untuk gambaran umum `rojak-pantau` ada di #10 

Untuk `rojak-analyzer`,  kira-kira gambaran besar step yang harus dilakuin seperti ini:
1. Menentukan jenis-jenis sentimen nya
2. Mengumpulkan training data (Berita + label sentimen nya)
3. Benchmark metode untuk sentiment analysis nya. Kita akan menggunakan metode yang menghasilkan model dengan akurasi terbaik (dan beberapa metrics lainnya). 

Step 1 kita diskusikan bersama, Step 2 bersamaan secara parallel dengan akhirnya menggabungkan data yang di dapat jadi satu, Step 3 kita masing-masing usul metode apa yang dipakai beserta link ke papersnya (untuk refrensi yang lain). Step 3 yang akan sangat menyenangkan hehe :).

Kira-kira gambaran besarnya nanti seperti itu, semoga kedengarannya menyenangkan!

 yup mungkin step ngumpulin dan labelin data yang memakan waktu dan paling membosankan hehe. However dengan kita melakukannya bersama-sama kita harap bisa lebih sedikit seru! :).

Silahkan lihat masing-masing github issue yang lain untuk lebih detailnya.

Kalau ada pertannyaan feel free to comment below

**Comment by Teofebano19** [comment]
@pyk : sori banget Bay gw masih noob banget, jadi butuh beberapa penjelasan wkwkwk 
1. Stack yang lu maksud itu gimana ya? Digunakan untuk apa sih yang jadi pertanyaan dasarnya
2. Untuk benchmark sendiri, lu udah ada referensi awal? Kalo ada, mau minta papernya biar dapet gambaran dulu sebenernya metode yang sekiranya ada dan cukup jitu

hehehe

**Comment by vck** [comment]
@pyk nyimak :smile:

**Comment by pyk** [comment]
@Teofebano19 maaf ya mas kemaren belum sempet kasih link ke stack yang aku maksut jadi kurang jelas. Contohnya seperti ini mas kalo yang Sayoeti kemaren  https://gitlab.com/bay/sayoeti-pantau Tenang mas nanti kita bahas lebih detail lagi, step by step yah 👍 

> Untuk benchmark sendiri, lu udah ada referensi awal? Kalo ada, mau minta papernya biar dapet gambaran dulu sebenernya metode yang sekiranya ada dan cukup jitu

Ada mas, rencananya aku pake fasttext. Papernya https://arxiv.org/pdf/1607.04606v1.pdf https://arxiv.org/pdf/1607.01759v2.pdf
Jadi nanti tiap tim data kita muncul dengan metode sendiri gitu mas, pasti seru 😄

**Comment by linggom** [comment]
@pyk untuk yang fasttext data source nya dari wikipedia juga ?

**Comment by pyk** [comment]
@linggom maksutnya data training mas?

**Comment by fawwaz** [comment]
Belum ada datanya ya ? Ini berarti statusnya nunggu sampe ada yang bisa ngescrape berarti ? @pyk

**Comment by imrenagi** [comment]
@fawwaz belum ada mestinya. Tapi buat skrg, kita mungkin udah bisa mulai bikin scrappernya

**Comment by pyk** [comment]
@fawwaz belum mas, bener kata @imrenagi. Expect minggu ini udah ada datanya lah buat di labelin. Lagi persiapin dasar semuanya dulu #18 #17 #10

**Comment by pyk** [comment]
Oh ya, untuk yang belum join slack Rojak Team untuk diskusi/tanya2 bisa gabung lewat sini https://rojakteam.herokuapp.com/, nuhun 🙇

**Comment by irwansyahwii** [comment]
Numpang nyimak

**Comment by pyk** [comment]
Ini kita close ya, udah reach milestone `Rojak v1.0.0`. next step, kita akan diskusi tentang `Rojak v2.0.0`, mostly penyempurnaan aja.
