### ISSUE TITLE
rojak-pantau dependencies

### ISSUE THREAD

**Issue by rawgni** [pyk/rojak#53]
```
Collecting MySQL-python==1.2.5 (from -r requirements.txt (line 12))
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hA76Ps/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hA76Ps/MySQL-python/
```

**Steps to reproduce**:
`./install_dependencies.sh`

**Comment by girikuncoro** [comment]
@rawgni what's your machine/environment? can you confirm you have `mysql` installed on your machine? `mysql_config` is something related to your `mysql` installation, not the `pip` thing

this might help:

```
apt-get install libmysqlclient-dev python-dev
```

http://stackoverflow.com/questions/7475223/mysql-config-not-found-when-installing-mysqldb-python-interface

**Comment by rawgni** [comment]
@girikuncoro yep it's not installed. 

Maybe there should be one script to setup dev/prod env. what do you think?

**Comment by girikuncoro** [comment]
@rawgni good idea, I'm planning to wrap it up with `virtualenv`, `nose`, and `flake8` as well. close for now

**Comment by girikuncoro** [comment]
@rawgni also actually you might wanna setup `rojak-database` as well if you're planning to start playing with `rojak-pantau` as stated here: https://github.com/pyk/rojak/tree/master/rojak-pantau#setup
