### ISSUE TITLE
Rojak Apps

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#6]
Mas @vickydasta bisa kasih brief disini nanti android appnya bagaimana, stack, requirement dll

**Comment by vck** [comment]
@pyk karena bentuk data nya masih belum nampak, saya belum bisa ngebayangin mau pake apa aja. yang pasti, untuk koneksi ke **rojak-api**, kita make [retrofit](http://square.github.io/retrofit/)

**Comment by pyk** [comment]
@vickydasta sep! 🙇 

Tim data akan fix schema dulu #2 biar Tim API bisa buat mockup API nya #4

**Comment by vck** [comment]
@pyk wokay!

**Comment by billyriantono** [comment]
boleh ikut kontribute di Android nya ? 😄

**Comment by vck** [comment]
@billyriantono boleh banget mas :smiley:

**Comment by anta40** [comment]
ikutan nyimak yak...

**Comment by mychaelgo** [comment]
@vickydasta retrofit berapa ya gan? :)

**Comment by vck** [comment]
@mychaelgo retrofit 2

**Comment by mychaelgo** [comment]
@vickydasta ok gan :) noted

**Comment by pyk** [comment]
guys schema versi awal udah ready ya #9, tinggal tunggu mockup dari tim api #4 . Nuhun 🙇

**Comment by hidrodixtion** [comment]
Siap bantu kontribusi di Android, atau semisal juga ingin merambah iOS 😁

**Comment by vck** [comment]
@hidrodixtion _appreciate_ bgt!

**Comment by anta40** [comment]
Kira2 ada isu kah kalau sebagian develop pakai Eclipse, sedangkan sebagian yang lain pakai Android Studio?
Android Studio di laptop saya lelet betul huhuhu...

**Comment by vck** [comment]
ini project kolaborasi pertama saya, sebelumnya belum pernah _nge dev
android_ bareng, apalagi beda IDE.

**Comment by riordhn** [comment]
Kalau setahu saya ketika beda IDE permasalahan besarnya adalah build tools-nya
Setahu saya android menggunakan build tools gradle dan punya struktur project yang beda dengan eclipse CMIIW @vickydasta @anta40 @pyk
Nuhun🙏🙏

**Comment by vck** [comment]
@riordhn ya, rite. di [SO](http://stackoverflow.com/questions/17431838/android-studio-project-structure-v-s-eclipse-project-structure) sudah dibahas juga mengenai hal ini

**Comment by anta40** [comment]
ya wes kalau begitu saya ikut mayoritas mau pakai IDE yg mana deh ☺️

**Comment by billyriantono** [comment]
mungkin mas @vickydasta bisa list / share semacam kurang lebih apa saja yang bakal digunakan serta mungkin ada standarisasi untuk variable naming segala macamnya ( code convention ) ?

**Comment by mnafian** [comment]
Siap mbantu untuk bagian android, mungkin perlu di breaf lagi masalah standarisasi pengunaan pattern project yg dipakai? semisal mau pake MVP atau MVVM? atau mas @vickydasta udah buat standarisasi lainnya mungkin?

**Comment by vck** [comment]
@mnafian 
- untuk pattern apps nya, saya belum pernah make baik MVP, atau MVVP,
  mungkin temen-temen bisa bantu soal ini? :)

@billyriantono 
- juga untuk standarisasi kode, saya juga belum pernah make _yang beginian_. tbh ini project _seriusan_ pertama saya, and i'm so excited! 

dan, mungkin temen-temen yang lain lebih berpengalaman dlm android development, bisa ngegantiin saya nge lead bagian rojak-apps :smile: 

cc @pyk

**Comment by mnafian** [comment]
Kalo saya pribadi lebih prefer MVP, selain nanti lebih readable sama clean juga rata-rata udah banyak yg move on ke pattern ini, lebih modular juga, but in case dipake di scale project middle - complex, maka dari itu juga perlu tau scale rojak ini sebesar apa ntar, pengalaman pake MVP ini kalo dipake di project yg kompleksitasnya nanggung, buang2 resource juga menurut saya. cmiiw.
bisa diliat di list architecture yg menurut saya dari approachnya udah mendekati kaya hasil penjelasan yigit boyar di google I/O kemaren :

https://github.com/googlesamples/android-architecture

[EDIT] : approach yang ini bagus juga buat dipake, penjelasan lebih lengkap dari yigit juga :
https://github.com/yigit/dev-summit-architecture-demo

**Comment by pyk** [comment]
@vickydasta yg ngelead cuma untuk komunikasi biar lancar mas, feel free untuk diskusiin apa aja kebutuhannya sama tim 😃

**Comment by pyk** [comment]
Oh ya, untuk yang belum join slack Rojak Team untuk diskusi/tanya2 bisa gabung lewat sini https://rojakteam.herokuapp.com/, nuhun 🙇

**Comment by vck** [comment]
woke!

On Sat, Oct 8, 2016 at 12:37 AM, Bayu Aldi Yansyah <notifications@github.com

**Comment by pyk** [comment]
Ini kita close ya, udah reach milestone `Rojak v1.0.0`. next step, kita akan diskusi tentang `Rojak v2.0.0`, mostly penyempurnaan aja.
