### ISSUE TITLE
[rojak-pantau] Fail-safe untuk rojak-pantau

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#64]
Untuk sekarang ini spider kita assume kalau elemen yg di ambil (`response.css('nama class')`) itu ada sih

Nah ada beberapa kasus misalnya response webnya `404`, itu nanti `title`,`author_name` etc itu bakalan empty/NULL.

Jadi kita harus nambahin untuk Fail-safe, kalau ada `title` etc yg kosong, kita raise `DropItem` https://doc.scrapy.org/en/latest/topics/exceptions.html#dropitem

Menurut kalian gimana? @girikuncoro @imrenagi @kevinluvian @rawgni

**Comment by imrenagi** [comment]
Setuju.

**Comment by rawgni** [comment]
setuju

**Comment by girikuncoro** [comment]
Setuju, tinggal dimasukin ke pipeline aja kan ya? Ohya tapi metrotvnews apa cnn gitu kalo gak salah ada page yg ga ada authornya (kalo video, gw ambil captionnya 1-2 paragraf, tapi karena video dia ga ada author), ini bagusnya diilangin apa gw kasih nama dummy aja?

**Comment by girikuncoro** [comment]
dan kalo response 404 etc page nya itu ke catch terus scraping nya lanjut, atau bakal raise error terus berenti? belom sempet ngetes euy

**Comment by pyk** [comment]
> Setuju, tinggal dimasukin ke pipeline aja kan ya?

Rencananya gitu mas, tapi mostly fail nya gara2 index out-of-bond (access index `0` dari empty string). Jadi tetep di spider-nya

>  Ohya tapi metrotvnews apa cnn gitu kalo gak salah ada page yg ga ada authornya (kalo video, gw ambil captionnya 1-2 paragraf, tapi karena video dia ga ada author), ini bagusnya diilangin apa gw kasih nama dummy aja?

Jangan mas, kalo gak ada authornya di skip aja. Author salah satu feature training data kita btw

> dan kalo response 404 etc page nya itu ke catch terus scraping nya lanjut, atau bakal raise error terus berenti? belom sempet ngetes euy

Kita raise `DropItem` mas. Scrape lanjut tapi news kita skip

**Comment by pyk** [comment]
btw kalo gitu nanti malem aku submit PR ya tentang ini, terimakasih! :bowing_man:

**Comment by kevinluvian** [comment]
:ok_hand:

**Comment by pyk** [comment]
Need to implement this to other spiders, will create separate issue for this.
