### ISSUE TITLE
[rojak-pantau] Create a database service for rojak-pantau

### ISSUE THREAD

**Issue by imrenagi** [pyk/rojak#65]
Currently, each scrapper creates their own mysql implementation. I think we need to separate this thing so that all scrapper can use the similar function from a service to store the result to the database. Otherwise, we will end up with changing every scrapper when we update the query or database schema.

**Comment by pyk** [comment]
setuju, mungkin separate package mirip [i18n](https://github.com/pyk/rojak/tree/master/rojak-pantau/rojak_pantau/i18n) yah

cc: @girikuncoro

**Comment by girikuncoro** [comment]
@pyk @imrenagi  hmm kurang paham, ini maksudnya ngomong [ini](https://github.com/pyk/rojak/blob/master/rojak-pantau/rojak_pantau/spiders/detikcom.py#L22) dan [ini](https://github.com/pyk/rojak/blob/master/rojak-pantau/rojak_pantau/spiders/detikcom.py#L26)?

**Comment by girikuncoro** [comment]
sama sbnernya kalo mau enhancement kepikiran kalo `__init__`, `from_crawler`, `spider_opened`, `spider_closed` untuk setiap spider semuanya sama, jadi bisa dijadiin base/parent class aja tiap spider news cukup implement `parse` sama `parse_news`

**Comment by girikuncoro** [comment]
wah gerak cepat @rawgni :D

**Comment by pyk** [comment]
@imrenagi yg #69 udah fix ini kan?
