### ISSUE TITLE
[rojak-ui] Sebagai pengguna rojak, saya ingin melihat searchbox dan beberapa kategori pencarian.

### ISSUE THREAD

**Issue by chi-putera** [pyk/rojak#66]
![rojakhome](https://cloud.githubusercontent.com/assets/8364545/19334739/71ce5c6c-9128-11e6-803d-7d14dde941f1.jpg)

Requirements:
- Interaksi bisa serupa dengan https://libscore.com/.
- Ada penjelasan singkat mengenai cara penggunaan aplikasi.
- Fitur hasil pencarian akan dipisah pada _story (issue)_ lain.

**Comment by adrianha** [comment]
Please review #109 yah @CodeRiderz @rromadhoni

**Comment by bobbypriam** [comment]
Boleh info lebih jauh untuk story ini butuh apa saja dari API? Spesifikasi API sampai saat ini belum meng-_cater_ fitur pencarian.

Ini sepertinya cuma pencarian media, kandidat, dan pasangan ya? Karena jumlah masing-masing kategori tersebut terbatas (tidak seperti berita yang banyak sekali), apa mungkin API hanya perlu mengembalikan semua data dan kemudian pencarian/filtering dilakukan di client? Atau benar-benar harus ada API untuk full-text search?

cc: @pyk, andaikan full-text search, di MySQL (`LIKE '%foo%'`) kayaknya ga akan terlalu performant ya

**Comment by chi-putera** [comment]
Iyes om, seharusnya cukup dilakukan di client side.
**Mungkin nanti** kita akan butuh fitur search hanya untuk `/news` saja.

**Comment by pyk** [comment]
> andaikan full-text search, di MySQL (LIKE '%foo%') kayaknya ga akan terlalu performant ya

@bobbypriambodo yup bener
