### ISSUE TITLE
Rojak UI Relawan

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#7]
Yo @riordhn bisa kamu brief disini gimana relawan botnya, stack, requirement dll

**Comment by riordhn** [comment]
Okee Bay @pyk, untuk rojak UI relawan ini nanti konsep nya bakal seperti BOT auto comment di facebook. Di mana output yang diharapkan adalah tingkat sentimen dari suatu media dapat diukur dan memberikan berita penyeimbang maupun yang terkait dengan berita yang ada.

Case : Salah satu dari teman fb relawan rojak men-share berita dari suatu media yang mendukung satu pasangan calon. BOT fb yang merupakan bagian dari rojak bakal read berita tersebut dan menjadikan hal tersebut suatu input parameter. rojak melalui BOT fb nya bakal memberikan tingkat sentimen dari media yang di-share dan memberikan berita terkait lainnya.
Ekspektasi dari relawan rojak secara singkat sih.
Feel free to open discuss
Buat schema proses nya secepatnya menyusul nya :)

**Comment by pyk** [comment]
@riordhn thanks yo! keep us updated yah 👍

**Comment by christoga** [comment]
Botnya messenger kan? udah jadi belom?

**Comment by christoga** [comment]
Saya waktu itu pernah bikin sih bareng temen saya pas di facebook hackathon, https://github.com/star-ters/bot

**Comment by riordhn** [comment]
@christoga Thanks banget mas chris.
Sejauh ini masih uji coba juga kok mas

**Comment by ghost** [comment]
Sama-sama @riordhn 
Oh iya, jangan panggil mas :joy:

Masih muda 😂 😂 😂

**Comment by vck** [comment]
😂😂😂

**Comment by christoga** [comment]
Bro, online messenger lu?

**Comment by vck** [comment]
telegram

**Comment by christoga** [comment]
Ini kenapa gak gunain GitHub Projects ya? biar lebih gampang

**Comment by famasya** [comment]
question mas @riordhn , berita penyeimbangnya itu nanti punya sentimen netral kah?
Lalu penyeimbangnya saran juga dalam konteks yang sama. Ex: penggusuran

**Comment by pyk** [comment]
@christoga wah kamu yg di FB hackathon kemaren ya? keren2. Boleh tuh messenger botnya 👍 

> Ini kenapa gak gunain GitHub Projects ya? biar lebih gampang

Yup bener, nanti kalo issuenya udah banyak lebih baik pake github projects

**Comment by pyk** [comment]
Oh ya, untuk yang belum join slack Rojak Team untuk diskusi/tanya2 bisa gabung lewat sini https://rojakteam.herokuapp.com/, nuhun 🙇

**Comment by pyk** [comment]
@riordhn any update yo?

**Comment by girikuncoro** [comment]
agak bingung soal ide yang bot ini, apakah ini melakukan:
- mantau artikel2 di fb yang terkait sama pilgub, scrape dan masuk ke `rojak-database`, atau
- mantau artikel2 terkait di fb, lalu beri sentimen text dan juga fitur2 lain (e.g. jumlah share, jumlah comment, jumlah like), kasih sentimen komen2 nya juga sebagai input `rojak-analyzer`, atau
- sebagai interface masyarakat -> tanya2 lewat bot messenger platform conversational, atau
- semua dimulai dari berita yang dishare oleh relawan rojak (profile2 fb nya preregistered?), lalu dipantau responnya (likes, share, etc.)

yang manakah? mainannya banyak ke Graph API kah atau Messenger platform? ini sepertinya lebih cocok masuk ke `tim-data`? :D

**Comment by ghost** [comment]
Nanyanya di slack aja mas😉

**Comment by girikuncoro** [comment]
aku mulei kerjain ini hari sabtu ya

**Comment by girikuncoro** [comment]
@pyk belum bisa rupanya, depends on `http://api.rojak.id/v1/news?embed[]=mentions` sama `http://api.rojak.id/v1/media/1/sentiments` sepertinya

**Comment by pyk** [comment]
Ini kita close ya, udah reach milestone `Rojak v1.0.0`. next step, kita akan diskusi tentang `Rojak v2.0.0`, mostly penyempurnaan aja.

@girikuncoro nanti kita diskusikan di`Rojak v2.0.0` ya mas
