### ISSUE TITLE
[rojak-pantau] Bug on spiders, class not imported

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#71]
It seems this missed on #69 , will fix this on the next PR https://github.com/pyk/rojak/blob/master/rojak-pantau/rojak_pantau/spiders/detikcom.py#L44

**Comment by girikuncoro** [comment]
tinggal tambah `from scrapy import Request`

**Comment by pyk** [comment]
yup bener mas 🙇

**Comment by pyk** [comment]
Fixed by #73
