### ISSUE TITLE
[rojak-analyzer] Required data

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#75]
Kita sebelumnya pernah diskusi di channel `#tim-data` untuk topik ini: (copy paste)

```
jadi gini:
1. It’s possible untuk menentukan bias media dengan sentiment analytics beritanya saja. 
yg penting Author beritanya di perthatikan, karena memperngaruhi gaya bahasa dan lain lain.
2. Sentiment `pro/contra` itu rada tricky sih, contohnya seperti beritanya agus di atas. 
Tapi kalo kita pake plain `positif/negatif` itu semakin jelas. 
Jelas beritanya positif mengenai Agus
```

nah waktu itu aku hanya kepikiran classifier untuk satu media aja sih, itu mungkin untuk pake data `author_name` sebagai feature.

Setelah aku coba, ada beberapa masalah untuk approach ini:
1. Kita harus buat satu media satu classifier => very time consuming
2. Kita harus punya daftar author untuk setiap media (berdasarkan hasil dari #39 banyak media yg gak punya author)

Nah untuk sekarang `rojak-analyzer` cuman butuh 1 classifier saja sih untuk semua media. jadi kita hanya pakai data `raw_content` aja untuk training nya.

Menurut kalian gimana? feel free to comment yeah 🙇

**Comment by kevinluvian** [comment]
kalo pake author_name sebagai feature, apakah ngak nanti classifiernya jadi bias? (melihat pro/kontra nya dari artikel author sebelumnya, padahal yang mau di classify adalah artikel author pada saat itu, exclusive dari artikel lain author tsb)

pertimbangan mau pakai author untuk jadi feature apa ya? aku pikir lebih bagus kalo gak bias?

**Comment by pyk** [comment]
@kevinluvian Yup, untuk satu media itu yang mau kita capture mas (dengan pertimbangan gaya bahasa author, keberpihakan, dll). Tapi kalau kasus rojak ini ada beberapa media jadi kita gak bisa pakai `author_name` mas. Karena belum tentu author A menulis berita di semua media.

Jadi kita gak pake lagi feature `author_name`

**Comment by kevinluvian** [comment]
ooh jadi issuenya karena syarat untuk jadi feature itu harus universal ya? author harus tulis berita di semua media?
yah kalo gitu mau gak mau ga bisa pake feature author

**Comment by pyk** [comment]
@kevinluvian yup bener mas,

btw ini udah fix ya, #128
