### ISSUE TITLE
[rojak-pantau] Issue raw_content di CNN Indonesia

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#92]
Di dalam HTML tag `div.detail_text` [berita CNN Indonesia](http://m.cnnindonesia.com/politik/20161011132802-32-164701/agus-yudhoyono-blusukan-annisa-pohan-jadi-bintang/) ada beberapa element yang bukan content nya.

Seperti `date`, `title` `picdetail` dan `topiksisip`. Tantangan kita adalah untuk mengekstrak html content nya aja. 

Somehow kita harus exlude HTML tag yang bukan content itu.  

Aku rasa kita bisa menngunakan [XPath](https://doc.scrapy.org/en/latest/topics/selectors.html#constructing-selectors) selectors

Reference: [StackOverflow](http://stackoverflow.com/questions/27451550/how-to-select-all-children-text-but-excluding-a-tag-with-scapys-xpath)

**Comment by pyk** [comment]
Contoh penggunaan XPath ada disini https://github.com/pyk/rojak/blob/master/rojak-pantau/rojak_pantau/spiders/detikcom.py#L91

**Comment by girikuncoro** [comment]
I'm taking this

**Comment by pyk** [comment]
ini fixed by #105 yah
