### ISSUE TITLE
[rojak-pantau] Invalid raw_content dan masalah di author_name pada Kompas

### ISSUE THREAD

**Issue by pyk** [pyk/rojak#94]
Untuk sekarang scraper kompas kita masih mengambil `raw_data` yg invalid. 

Contohnya berita ini: [http://megapolitan.kompas.com/read/2016/10/14/20230371/sylviana.murni.sindir.ahok.lebih.banyak.buat.pergub.daripada.perda](http://megapolitan.kompas.com/read/2016/10/14/20230371/sylviana.murni.sindir.ahok.lebih.banyak.buat.pergub.daripada.perda)

```
mysql> select * from news where media_id=2 limit 1\G
*************************** 1. row ***************************
          id: 655
    media_id: 2
       title: Sylviana Murni Sindir Ahok Lebih Banyak Buat Pergub daripada Perda
 raw_content: <p><strong>JAKARTA, KOMPAS.com</strong> — Bakal calon wakil gubernur DKI Jakarta <a target="_blank" class="inner-link" href="http://megapolitan.kompas.com/tag/Sylviana%20Murni" style="color:#428bca;">Sylviana Murni</a> secara tidak langsung menyindir Gubernur DKI Jakarta <a target="_blank" class="inner-link" href="http://megapolitan.kompas.com/tag/Basuki%20Tjahaja%20Purnama" style="color:#428bca;">Basuki Tjahaja Purnama</a> atau Ahok soal pembuatan aturan di Jakarta.</p>
         url: http://megapolitan.kompas.com/read/2016/10/14/20230371/sylviana.murni.sindir.ahok.lebih.banyak.buat.pergub.daripada.perda
 is_analyzed: 0
 author_name: Kahfi Dirga Cahya, Kompas TV
published_at: 2016-10-14 13:23:00
 inserted_at: 2016-10-15 17:59:37
  updated_at: 2016-10-15 17:59:37
1 row in set (0.00 sec)
```

Scraper kompas hanya mengambil sebagian `raw_content` dan `author_name` seharusnya tidak ada `Kompas TV` nya.

**Comment by pyk** [comment]
contoh penggunaan xpath ada di https://github.com/pyk/rojak/blob/master/rojak-pantau/rojak_pantau/spiders/detikcom.py#L91

**Comment by kevinluvian** [comment]
fyi: ada artikel yang multiple page
http://megapolitan.kompas.com/read/2016/10/15/07300081/ini.yang.akan.dilakukan.ahok-djarot.anies-sandi.dan.agus-sylvi.di.bidang.kesehatan

menurutku lebih baik kita pakai API kompas ini aja, returnnya langsung all page

http://api.kompas.com/external/?type=readdua&kanal=home&command=.xml.2016.10.15.07300081&format=json&APPSF0UNDRYBYPASS=%20HTTP/1.1

**Comment by pyk** [comment]
@kevinluvian woah, udah lengkap kalo pake API nya itu. Mantap 👍

**Comment by kevinluvian** [comment]
hmm saya ambil aja ya ini

**Comment by kevinluvian** [comment]
untuk field url nya mending url api atau url aslinya? @pyk 
dari api nya dapet sih link ke articlenya, tapi takutnya ga konsisten aja.

**Comment by bobbypriam** [comment]
Nimbrung, harusnya URL asli ga ya? Karena nantinya akan ada di response payload dari rojak-api untuk digunakan di UI (link menuju berita). CMIIW

**Comment by kevinluvian** [comment]
kalo misalnya bener harus url asli, ada beberapa spider yang harus diganti

**Comment by pyk** [comment]
@kevinluvian iya mas harus URL aslinya (url public ke berita)

**Comment by kevinluvian** [comment]
kalo gitu parser okezone harus dirubah @pyk, tapi ada beberapa parser yang pake link article versi mobilenya. kalo misalnya mau ditaro di UI harusnya bukan link mobile dong?

**Comment by pyk** [comment]
@kevinluvian untuk itu gak masalah sih mas, biasanya langsung di redirect ke versi non-mobilenya sama server media nya.

Ini fixed by #108 yah
